#!/bin/bash

#/ NAME
#/     build-cache-git -- build the git cache
#/
#/ SYNOPSIS
#/     build cache git

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

DEFINE_string cache "$VAULT/git-cache" "Git-repo cache home"
DEFINE_string repos "$PWD/config/git-cache.txt" "List of git-repos to cache"

# entry point
function main {
  unset GIT_SSH
  cd "$FLAGS_cache"
  runmany 8 1 '[[ -f $1/HEAD ]] || git mirror $1' $(cat "$FLAGS_repos") || true
  runmany 8 1 'cd $1 && git fetch --all' $(set +f; echo */*.git)
}

require sub "$BASH_SOURCE" "$@"
